{
   "swagger": "2.0",
   "info": {
      "x-ibm-name": "payments-api",
      "title": "Payments API",
      "description": "## MobilePay Payments API\r\nMobilePay Payments API makes it easy\nfor you to collect money from your customers using MobilePay.\r\n\r\n#### General\nnotes\r\nAll dates use the (`ISO 8601-1:2019`) format: date-time format - (`YYYY-MM-DDTHH:mm:ssZ`)\nor (`YYYY-MM-DDTHH:mm:ss+00:00`).\r\n",
      "version": "1.0.1",
      "contact": {
         "email": "developer@mobilepay.dk"
      }
   },
   "schemes": [
      "https"
   ],
   "basePath": "/",
   "consumes": [
      "application/json"
   ],
   "produces": [
      "application/json"
   ],
   "securityDefinitions": {
      "Client Id": {
         "type": "apiKey",
         "in": "header",
         "name": "X-IBM-Client-Id"
      }
   },
   "security": [
      {
         "Client Id": []
      }
   ],
   "x-ibm-configuration": {
      "testable": true,
      "enforced": true,
      "phase": "realized"
   },
   "paths": {
      "/v1/payments": {
         "post": {
            "tags": [
               "Payments"
            ],
            "summary": "Initiates a new payment.",
            "description": "<label>Request JSON body</label><table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>amount</code></td><td><strong>Required</strong></td><td>number\n(integer)</td><td>The amount of money to be collected by this payment.<br>A\npositive integer representing how much to charge in the smallest currency\nunit (e.g., 100 cents to charge â‚¬1.00). The minimum amount is 1. The maximum\namount is defined by user's daily/yearly limits.\n\n</td></tr><tr><td><code>idempotencyKey</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>A unique value that identifies this InitiatePayment request.\nMust be a valid GUID, and is used to protect against accidental duplicate\ncalls. Multiple requests with the same idempotency key have the same result.\n\n</td></tr><tr><td><code>paymentPointId</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>The Payment Point ID to associate with a payment.\n\n</td></tr><tr><td><code>redirectUri</code></td><td><strong>Required</strong></td><td>string</td><td>MobilePay\nwill use the redirectUri URL to redirect the MobilePay user to the merchant's\nconfirmation page once user action is completed in MobilePay app. Must be\na valid URI.</td></tr><tr><td><code>reference</code></td><td><strong>Required</strong></td><td>string</td><td>An\nID to associate with the payment. Max length: 64 characters.<br />\r\nYou\ncan use this field to associate the payment to an entity in an external system\n(for example, you might specify an order ID that is generated by your system).\nIt is recommended to use a unique value for each payment.\n\n</td></tr><tr><td><code>description</code></td><td>Optional</td><td>string</td><td>Optional\npayment information to be displayed in MobilePay app to the customer. Max\nlength: 200 characters.<br />\r\nThis can be, for example, an invoice number,\nticket number, or short description that uniquely identifies the purchase.\n\n</td></tr></tbody></table>\n\n<label>Request\nJSON example</label>\n\n```json\r\n{\r\n  \"amount\": 1250,\r\n  \"description\":\n\"Lorem ipsum dolor sit amet, consectetur adipiscing elit.\",\r\n  \"paymentPointId\":\n\"7347ba06-95c5-4181-82e5-7c7a23609a0e\",\r\n  \"reference\": \"My-Payment-1\",\r\n\n \"idempotencyKey\": \"fae7680f-9875-4ba9-8910-2f2e1791f390\",\r\n  \"redirectUri\":\n\"myapp://redirect\",\r\n}\r\n```\n\r\n<label>Response JSON body</label><table\nstyle=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>mobilePayAppRedirectUri</code></td><td><strong>Required</strong></td><td>string</td><td>Deeplink\nto MobilePay app.\n\n</td></tr><tr><td><code>paymentId</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>A unique ID for the payment.\n\n</td></tr></tbody></table>\n\n<label>Response\nJSON example</label>\n\n```json\r\n{\r\n  \"paymentId\": \"186d2b31-ff25-4414-9fd1-bfe9807fa8b7\",\r\n\n \"mobilePayAppRedirectUri\": \"mobilepay://merchant_payments?payment_id=186d2b31-ff25-4414-9fd1-bfe9807fa8b7\"\r\n}\r\n```\n\r\n",
            "consumes": [
               "application/json"
            ],
            "produces": [
               "application/json"
            ],
            "parameters": [
               {
                  "in": "header",
                  "name": "CorrelationId",
                  "description": "CorrelationId used for logging",
                  "type": "string"
               },
               {
                  "in": "header",
                  "name": "Authorization",
                  "description": "Bearer token (JWT or API key)",
                  "required": true,
                  "type": "string"
               },
               {
                  "in": "body",
                  "name": "body",
                  "schema": {
                     "$ref": "#/definitions/InitiatePaymentRequest"
                  }
               }
            ],
            "responses": {
               "200": {
                  "description": "",
                  "schema": {
                     "$ref": "#/definitions/InitiatePaymentResponse"
                  },
                  "examples": {
                     "application/json": {
                        "paymentId": "186d2b31-ff25-4414-9fd1-bfe9807fa8b7",
                        "mobilePayAppRedirectUri": "mobilepay://merchant_payments?payment_id=186d2b31-ff25-4414-9fd1-bfe9807fa8b7"
                     }
                  }
               },
               "400": {
                  "description": "",
                  "schema": {
                     "$ref": "#/definitions/ErrorResponse"
                  },
                  "examples": {
                     "application/json": {
                        "code": "1234",
                        "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "correlationId": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd",
                        "origin": "MPY"
                     }
                  }
               },
               "401": {
                  "description": "Unauthorized"
               },
               "403": {
                  "description": "Forbidden"
               },
               "409": {
                  "description": "Conflict",
                  "schema": {
                     "$ref": "#/definitions/ErrorResponse"
                  },
                  "examples": {
                     "application/json": {
                        "code": "1234",
                        "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "correlationId": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd",
                        "origin": "MPY"
                     }
                  }
               }
            }
         },
         "get": {
            "tags": [
               "Payments"
            ],
            "summary": "Gets a list of all merchant payments if no filters(e.g. stateFilter,\nstartDate, endDate, paymentPointId) are provided. Can also return only payments\nof specific payment point if paymentPointId is provided.",
            "description": "<label>Response JSON body</label><table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>pageSize</code></td><td><strong>Required</strong></td><td>number (integer)</td><td>The number of payments per page. The range is 1 to 1000.\n\n</td></tr><tr><td><code>payments</code></td><td><strong>Required</strong></td><td>array of <code>GetSinglePaymentResponse</code></td><td>The requested list of payments.\n\n</td></tr><tr><td><code>nextPageNumber</code></td><td>Optional</td><td>number (integer)</td><td>A number of the next page. The null value indicates that the response has the last page.\n\n</td></tr></tbody></table>\n\n<label>Response JSON example</label>\n\n```json\n{\n  \"pageSize\": 1,\n  \"nextPageNumber\": 2,\n  \"payments\": [\n    {\n      \"paymentId\": \"186d2b31-ff25-4414-9fd1-bfe9807fa8b7\",\n      \"amount\": 1250,\n      \"description\": \"Lorem ipsum dolor sit amet, consectetur adipiscing elit.\",\n      \"paymentPointId\": \"7347ba06-95c5-4181-82e5-7c7a23609a0e\",\n      \"reference\": \"My-Payment-1\",\n      \"mobilePayAppRedirectUri\": \"mobilepay://merchant_payments?payment_id=186d2b31-ff25-4414-9fd1-bfe9807fa8b7\",\n      \"state\": \"initiated\",\n      \"initiatedOn\": \"2021-09-27T08:42:22Z\",\n      \"lastUpdatedOn\": \"2021-09-27T08:42:22Z\",\n      \"merchantId\": \"655ad36f-70b0-4add-a123-b943daca50e8\",\n      \"isoCurrencyCode\": \"DKK\",\n      \"paymentPointName\": \"MyPaymentPoint\"\n    }\n  ]\n}\n```\n\n",
            "produces": [
               "application/json"
            ],
            "parameters": [
               {
                  "in": "query",
                  "name": "paymentPointId",
                  "description": "Filter specific payment point payments",
                  "type": "string",
                  "format": "uuid"
               },
               {
                  "in": "query",
                  "name": "pageNumber",
                  "description": "Default and minimum value is 1. Values that are less than 1 will\nbe replaced by 1.",
                  "type": "integer",
                  "format": "int32"
               },
               {
                  "in": "query",
                  "name": "pageSize",
                  "description": "Number of payments to be returned. Between 1 and 1000.",
                  "type": "integer",
                  "format": "int32"
               },
               {
                  "in": "query",
                  "name": "stateFilter",
                  "description": "Filter payments by state. Allowed values: \"initiated\", \"reserved\",\n\"captured\", \"cancelledByMerchant\", \"cancelledByUser.",
                  "type": "array",
                  "items": {
                     "enum": [
                        "initiated",
                        "reserved",
                        "captured",
                        "cancelledByMerchant",
                        "cancelledByUser",
                        "cancelledBySystem"
                     ],
                     "type": "string"
                  }
               },
               {
                  "in": "query",
                  "name": "startDate",
                  "description": "Filter payments by InitiatedOn property.",
                  "type": "string",
                  "format": "date-time"
               },
               {
                  "in": "query",
                  "name": "endDate",
                  "description": "Filter payments by InitiatedOn property.",
                  "type": "string",
                  "format": "date-time"
               },
               {
                  "in": "header",
                  "name": "CorrelationId",
                  "description": "CorrelationId used for logging",
                  "type": "string"
               },
               {
                  "in": "header",
                  "name": "Authorization",
                  "description": "Bearer token (JWT or API key)",
                  "required": true,
                  "type": "string"
               }
            ],
            "responses": {
               "200": {
                  "description": "",
                  "schema": {
                     "$ref": "#/definitions/GetPaymentsResponse"
                  },
                  "examples": {
                     "application/json": {
                        "pageSize": 1,
                        "nextPageNumber": 2,
                        "payments": [
                           {
                              "paymentId": "186d2b31-ff25-4414-9fd1-bfe9807fa8b7",
                              "amount": 1250,
                              "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                              "paymentPointId": "7347ba06-95c5-4181-82e5-7c7a23609a0e",
                              "reference": "My-Payment-1",
                              "mobilePayAppRedirectUri": "mobilepay://merchant_payments?payment_id=186d2b31-ff25-4414-9fd1-bfe9807fa8b7",
                              "state": "initiated",
                              "initiatedOn": "2021-09-27T08:42:22Z",
                              "lastUpdatedOn": "2021-09-27T08:42:22Z",
                              "merchantId": "655ad36f-70b0-4add-a123-b943daca50e8",
                              "isoCurrencyCode": "DKK",
                              "paymentPointName": "MyPaymentPoint"
                           }
                        ]
                     }
                  }
               },
               "400": {
                  "description": "",
                  "schema": {
                     "$ref": "#/definitions/ErrorResponse"
                  },
                  "examples": {
                     "application/json": {
                        "code": "1234",
                        "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "correlationId": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd",
                        "origin": "MPY"
                     }
                  }
               },
               "401": {
                  "description": "Unauthorized"
               },
               "409": {
                  "description": "PaymentPoint does not exists"
               }
            }
         }
      },
      "/v1/payments/{paymentid}": {
         "get": {
            "tags": [
               "Payments"
            ],
            "summary": "Gets a single payment by its ID.",
            "description": "<label>Response JSON body</label><table style=\"table-layout:\nauto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>amount</code></td><td><strong>Required</strong></td><td>number\n(integer)</td><td>The amount of money to be collected by this payment.<br>A\npositive integer representing how much to charge in the smallest currency\nunit (e.g., 100 cents to charge â‚¬1.00). The minimum amount is 1. The maximum\namount is defined by user's daily/yearly limits.\n\n</td></tr><tr><td><code>initiatedOn</code></td><td><strong>Required</strong></td><td>string\n(date-time)</td><td>The timestamp of when the payment was created, in ISO\n8601-1:2019 format.<br />\r\nExamples for July 19th, 2021 12:42:38am Pacific\nStandard Time:<br />\r\nUTC: 2021-07-19T12:42:38Z\n\n</td></tr><tr><td><code>isoCurrencyCode</code></td><td><strong>Required</strong></td><td>string</td><td>Three-letter\n<a href=\"https://www.iso.org/iso-4217-currency-codes.html\">ISO currency\ncode</a>, in uppercase.<br />\r\nPossible values:<br />\r\n\"DKK\",<br />\r\n\"EUR\"\n\n</td></tr><tr><td><code>lastUpdatedOn</code></td><td><strong>Required</strong></td><td>string\n(date-time)</td><td>The timestamp of when the payment was created, in ISO\n8601-1:2019 format.\n\n</td></tr><tr><td><code>merchantId</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>Merchant ID associated with the payment.\n\n</td></tr><tr><td><code>mobilePayAppRedirectUri</code></td><td><strong>Required</strong></td><td>string</td><td>Deeplink\nis used to redirect MobilePay users back to the merchant's app.\n\n</td></tr><tr><td><code>paymentId</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>The ID of the payment.\n\n</td></tr><tr><td><code>paymentPointId</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>The payment point on which payment was initiated.\n\n</td></tr><tr><td><code>paymentPointName</code></td><td><strong>Required</strong></td><td>string</td><td>Payment\npoint name displayed to the user in MobilePay app.\n\n</td></tr><tr><td><code>state</code></td><td><strong>Required</strong></td><td>string</td><td>Indicates\nwhether the payment is \"initiated\", \"reserved\", \"captured\", \"cancelledByMerchant\",\n\"cancelledBySystem\", \"cancelledByUser\".\n\n</td></tr><tr><td><code>description</code></td><td>Optional</td><td>string</td><td>Optional\npayment information to be displayed in MobilePay app to the customer. This\ncan be, for example, an invoice number, ticket number, or short description\nthat uniquely identifies the purchase.\n\n</td></tr><tr><td><code>reference</code></td><td>Optional</td><td>string</td><td>Payment's\nreference provided by you.\n\n</td></tr></tbody></table>\n\n<label>Response\nJSON example</label>\n\n```json\r\n{\r\n  \"paymentId\": \"186d2b31-ff25-4414-9fd1-bfe9807fa8b7\",\r\n\n \"amount\": 1250,\r\n  \"description\": \"Lorem ipsum dolor sit amet, consectetur\nadipiscing elit.\",\r\n  \"paymentPointId\": \"7347ba06-95c5-4181-82e5-7c7a23609a0e\",\r\n\n \"reference\": \"My-Payment-1\",\r\n  \"mobilePayAppRedirectUri\": \"mobilepay://merchant_payments?payment_id=186d2b31-ff25-4414-9fd1-bfe9807fa8b7\",\r\n\n \"state\": \"initiated\",\r\n  \"initiatedOn\": \"2021-09-27T08:42:22Z\",\r\n\n \"lastUpdatedOn\": \"2021-09-27T08:42:22Z\",\r\n  \"merchantId\": \"655ad36f-70b0-4add-a123-b943daca50e8\",\r\n\n \"isoCurrencyCode\": \"DKK\",\r\n  \"paymentPointName\": \"MyPaymentPoint\"\r\n}\r\n```\n\r\n",
            "produces": [
               "application/json"
            ],
            "parameters": [
               {
                  "in": "path",
                  "name": "paymentid",
                  "required": true,
                  "type": "string",
                  "format": "uuid"
               },
               {
                  "in": "header",
                  "name": "CorrelationId",
                  "description": "CorrelationId used for logging",
                  "type": "string"
               },
               {
                  "in": "header",
                  "name": "Authorization",
                  "description": "Bearer token (JWT or API key)",
                  "required": true,
                  "type": "string"
               }
            ],
            "responses": {
               "200": {
                  "description": "",
                  "schema": {
                     "$ref": "#/definitions/GetSinglePaymentResponse"
                  },
                  "examples": {
                     "application/json": {
                        "paymentId": "186d2b31-ff25-4414-9fd1-bfe9807fa8b7",
                        "amount": 1250,
                        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "paymentPointId": "7347ba06-95c5-4181-82e5-7c7a23609a0e",
                        "reference": "My-Payment-1",
                        "mobilePayAppRedirectUri": "mobilepay://merchant_payments?payment_id=186d2b31-ff25-4414-9fd1-bfe9807fa8b7",
                        "state": "initiated",
                        "initiatedOn": "2021-09-27T08:42:22Z",
                        "lastUpdatedOn": "2021-09-27T08:42:22Z",
                        "merchantId": "655ad36f-70b0-4add-a123-b943daca50e8",
                        "isoCurrencyCode": "DKK",
                        "paymentPointName": "MyPaymentPoint"
                     }
                  }
               },
               "401": {
                  "description": "Unauthorized"
               },
               "404": {
                  "description": "Not Found"
               },
               "409": {
                  "description": "Domain error response"
               }
            }
         }
      },
      "/v1/payments/{paymentid}/capture": {
         "post": {
            "tags": [
               "Payments"
            ],
            "summary": "Capture specific payment",
            "description": "<label>Request JSON body</label><table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>amount</code></td><td><strong>Required</strong></td><td>number (integer)</td><td>The amount to be captured. A positive integer representing how much to capture in the smallest currency unit (e.g., 100 cents to capture â‚¬1.00). The minimum amount is 1.\n\n</td></tr></tbody></table>",
            "consumes": [
               "application/json"
            ],
            "produces": [
               "application/json"
            ],
            "parameters": [
               {
                  "in": "path",
                  "name": "paymentid",
                  "required": true,
                  "type": "string",
                  "format": "uuid"
               },
               {
                  "in": "header",
                  "name": "CorrelationId",
                  "description": "CorrelationId used for logging",
                  "type": "string"
               },
               {
                  "in": "header",
                  "name": "Authorization",
                  "description": "Bearer token (JWT or API key)",
                  "required": true,
                  "type": "string"
               },
               {
                  "in": "body",
                  "name": "body",
                  "schema": {
                     "$ref": "#/definitions/CapturePaymentRequest"
                  }
               }
            ],
            "responses": {
               "204": {
                  "description": "Success"
               },
               "400": {
                  "description": "Bad Request",
                  "schema": {
                     "$ref": "#/definitions/ErrorResponse"
                  },
                  "examples": {
                     "application/json": {
                        "code": "1234",
                        "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "correlationId": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd",
                        "origin": "MPY"
                     }
                  }
               },
               "401": {
                  "description": "Unauthorized"
               },
               "403": {
                  "description": "Forbidden"
               },
               "409": {
                  "description": "Conflict",
                  "schema": {
                     "$ref": "#/definitions/ErrorResponse"
                  },
                  "examples": {
                     "application/json": {
                        "code": "1234",
                        "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "correlationId": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd",
                        "origin": "MPY"
                     }
                  }
               },
               "500": {
                  "description": "Server Error"
               }
            }
         }
      },
      "/v1/payments/{paymentid}/cancel": {
         "post": {
            "tags": [
               "Payments"
            ],
            "summary": "Cancel specific payment",
            "produces": [
               "application/json"
            ],
            "parameters": [
               {
                  "in": "path",
                  "name": "paymentid",
                  "required": true,
                  "type": "string",
                  "format": "uuid"
               },
               {
                  "in": "header",
                  "name": "CorrelationId",
                  "description": "CorrelationId used for logging",
                  "type": "string"
               },
               {
                  "in": "header",
                  "name": "Authorization",
                  "description": "Bearer token (JWT or API key)",
                  "required": true,
                  "type": "string"
               }
            ],
            "responses": {
               "204": {
                  "description": "Success"
               },
               "400": {
                  "description": "Bad Request",
                  "schema": {
                     "$ref": "#/definitions/ErrorResponse"
                  },
                  "examples": {
                     "application/json": {
                        "code": "1234",
                        "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "correlationId": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd",
                        "origin": "MPY"
                     }
                  }
               },
               "401": {
                  "description": "Unauthorized"
               },
               "403": {
                  "description": "Forbidden"
               },
               "409": {
                  "description": "Conflict",
                  "schema": {
                     "$ref": "#/definitions/ErrorResponse"
                  },
                  "examples": {
                     "application/json": {
                        "code": "1234",
                        "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "correlationId": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd",
                        "origin": "MPY"
                     }
                  }
               }
            }
         }
      },
      "/v1/payments/cancel": {
         "post": {
            "tags": [
               "Payments"
            ],
            "summary": "Cancel specific payment using idempotency key",
            "description": "<label>Request JSON body</label><table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>idempotencyKey</code></td><td><strong>Required</strong></td><td>string (uuid)</td><td>The idempotency key identifying the payment to be canceled. Only payments in the initiated state can be canceled using the idempotency key.\n\n</td></tr></tbody></table>\n\n",
            "consumes": [
               "application/json"
            ],
            "produces": [
               "application/json"
            ],
            "parameters": [
               {
                  "in": "header",
                  "name": "CorrelationId",
                  "description": "CorrelationId used for logging",
                  "type": "string"
               },
               {
                  "in": "header",
                  "name": "Authorization",
                  "description": "Bearer token (JWT or API key)",
                  "required": true,
                  "type": "string"
               },
               {
                  "in": "body",
                  "name": "body",
                  "schema": {
                     "$ref": "#/definitions/CancelPaymentRequest"
                  }
               }
            ],
            "responses": {
               "204": {
                  "description": "Success"
               },
               "400": {
                  "description": "Bad Request",
                  "schema": {
                     "$ref": "#/definitions/ErrorResponse"
                  },
                  "examples": {
                     "application/json": {
                        "code": "1234",
                        "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "correlationId": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd",
                        "origin": "MPY"
                     }
                  }
               },
               "401": {
                  "description": "Unauthorized"
               },
               "403": {
                  "description": "Forbidden"
               },
               "409": {
                  "description": "Conflict",
                  "schema": {
                     "$ref": "#/definitions/ErrorResponse"
                  },
                  "examples": {
                     "application/json": {
                        "code": "1234",
                        "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                        "correlationId": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd",
                        "origin": "MPY"
                     }
                  }
               }
            }
         }
      }
   },
   "definitions": {
      "CancelPaymentRequest": {
         "description": "<table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>idempotencyKey</code></td><td><strong>Required</strong></td><td>string (uuid)</td><td>The idempotency key identifying the payment to be canceled. Only payments in the initiated state can be canceled using the idempotency key.\n\n</td></tr></tbody></table>\n\n",
         "required": [
            "idempotencyKey"
         ],
         "type": "object",
         "properties": {
            "idempotencyKey": {
               "format": "uuid",
               "description": "The idempotency key identifying the payment to be canceled. Only payments in the initiated state can be canceled using the idempotency key.\n\n",
               "type": "string"
            }
         }
      },
      "CapturePaymentRequest": {
         "description": "<table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>amount</code></td><td><strong>Required</strong></td><td>number\n(integer)</td><td>The amount to be captured. A positive integer representing\nhow much to capture in the smallest currency unit (e.g., 100 cents to capture\nâ‚¬1.00). The minimum amount is 1.</td></tr></tbody></table>",
         "required": [
            "amount"
         ],
         "type": "object",
         "properties": {
            "amount": {
               "format": "int32",
               "description": "The amount to be captured. A positive integer representing how much to capture in the smallest currency unit (e.g., 100 cents to capture â‚¬1.00). The minimum amount is 1.\n\n",
               "type": "integer"
            }
         }
      },
      "ErrorResponse": {
         "description": "<table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>code</code></td><td>Optional</td><td>string</td><td></td></tr><tr><td><code>correlationId</code></td><td>Optional</td><td>string</td><td></td></tr><tr><td><code>message</code></td><td>Optional</td><td>string</td><td></td></tr><tr><td><code>origin</code></td><td>Optional</td><td>string</td><td></td></tr></tbody></table>\n\n",
         "type": "object",
         "properties": {
            "code": {
               "description": "",
               "type": "string",
               "example": "1234"
            },
            "message": {
               "description": "",
               "type": "string",
               "example": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            "correlationId": {
               "description": "",
               "type": "string",
               "example": "91f2b05f-2171-4cea-9d5a-1cdbed6ae2cd"
            },
            "origin": {
               "description": "",
               "type": "string",
               "example": "MPY"
            }
         }
      },
      "GetPaymentsResponse": {
         "description": "<table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>pageSize</code></td><td><strong>Required</strong></td><td>number (integer)</td><td>The number of payments per page. The range is 1 to 1000.\n\n</td></tr><tr><td><code>payments</code></td><td><strong>Required</strong></td><td>array of <code>GetSinglePaymentResponse</code></td><td>The requested list of payments.\n\n</td></tr><tr><td><code>nextPageNumber</code></td><td>Optional</td><td>number (integer)</td><td>A number of the next page. The null value indicates that the response has the last page.\n\n</td></tr></tbody></table>\n\n",
         "required": [
            "pageSize",
            "payments"
         ],
         "type": "object",
         "properties": {
            "pageSize": {
               "format": "int32",
               "description": "The number of payments per page. The range is 1 to 1000.\n\n",
               "type": "integer",
               "example": 1
            },
            "nextPageNumber": {
               "format": "int32",
               "description": "A number of the next page. The null value indicates that the response has the last page.\n\n",
               "type": "integer",
               "example": 2
            },
            "payments": {
               "description": "The requested list of payments.\n\n",
               "type": "array",
               "items": {
                  "$ref": "#/definitions/GetSinglePaymentResponse"
               },
               "example": [
                  {
                     "PaymentId": "186d2b31-ff25-4414-9fd1-bfe9807fa8b7",
                     "Amount": 1250,
                     "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                     "PaymentPointId": "7347ba06-95c5-4181-82e5-7c7a23609a0e",
                     "Reference": "My-Payment-1",
                     "MobilePayAppRedirectUri": "mobilepay://merchant_payments?payment_id=186d2b31-ff25-4414-9fd1-bfe9807fa8b7",
                     "State": "initiated",
                     "InitiatedOn": "2021-09-27T11:42:22Z",
                     "LastUpdatedOn": "2021-09-27T11:42:22Z",
                     "MerchantId": "655ad36f-70b0-4add-a123-b943daca50e8",
                     "IsoCurrencyCode": "DKK",
                     "PaymentPointName": "MyPaymentPoint"
                  }
               ]
            }
         }
      },
      "GetSinglePaymentResponse": {
         "description": "<table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>amount</code></td><td><strong>Required</strong></td><td>number\n(integer)</td><td>The amount of money to be collected by this payment.<br>A\npositive integer representing how much to charge in the smallest currency unit\n(e.g., 100 cents to charge â‚¬1.00). The minimum amount is 1. The maximum amount\nis defined by user's daily/yearly limits.\n\n</td></tr><tr><td><code>initiatedOn</code></td><td><strong>Required</strong></td><td>string\n(date-time)</td><td>The timestamp of when the payment was created, in ISO 8601-1:2019\nformat.<br />\r\nExamples for July 19th, 2021 12:42:38am Pacific Standard Time:<br\n/>\r\nUTC: 2021-07-19T12:42:38Z\n\n</td></tr><tr><td><code>isoCurrencyCode</code></td><td><strong>Required</strong></td><td>string</td><td>Three-letter\n<a href=\"https://www.iso.org/iso-4217-currency-codes.html\">ISO currency code</a>,\nin uppercase.<br />\r\nPossible values:<br />\r\n\"DKK\",<br />\r\n\"EUR\"\n\n</td></tr><tr><td><code>lastUpdatedOn</code></td><td><strong>Required</strong></td><td>string\n(date-time)</td><td>The timestamp of when the payment was created, in ISO 8601-1:2019\nformat.\n\n</td></tr><tr><td><code>merchantId</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>Merchant ID associated with the payment.\n\n</td></tr><tr><td><code>mobilePayAppRedirectUri</code></td><td><strong>Required</strong></td><td>string</td><td>Deeplink\nis used to redirect MobilePay users back to the merchant's app.\n\n</td></tr><tr><td><code>paymentId</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>The ID of the payment.\n\n</td></tr><tr><td><code>paymentPointId</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>The payment point on which payment was initiated.\n\n</td></tr><tr><td><code>paymentPointName</code></td><td><strong>Required</strong></td><td>string</td><td>Payment\npoint name displayed to the user in MobilePay app.\n\n</td></tr><tr><td><code>state</code></td><td><strong>Required</strong></td><td>string</td><td>Indicates\nwhether the payment is \"initiated\", \"reserved\", \"captured\", \"cancelledByMerchant\",\n\"cancelledBySystem\", \"cancelledByUser\".\n\n</td></tr><tr><td><code>description</code></td><td>Optional</td><td>string</td><td>Optional\npayment information to be displayed in MobilePay app to the customer. This can\nbe, for example, an invoice number, ticket number, or short description that\nuniquely identifies the purchase.\n\n</td></tr><tr><td><code>reference</code></td><td>Optional</td><td>string</td><td>Payment's\nreference provided by you.\n\n</td></tr></tbody></table>\n\n",
         "required": [
            "amount",
            "initiatedOn",
            "isoCurrencyCode",
            "lastUpdatedOn",
            "merchantId",
            "mobilePayAppRedirectUri",
            "paymentId",
            "paymentPointId",
            "paymentPointName",
            "state"
         ],
         "type": "object",
         "properties": {
            "paymentId": {
               "format": "uuid",
               "description": "The ID of the payment.\n\n",
               "type": "string",
               "example": "186d2b31-ff25-4414-9fd1-bfe9807fa8b7"
            },
            "amount": {
               "format": "int32",
               "description": "The amount of money to be collected by this payment.<br>A positive integer representing how much to charge in the smallest currency unit (e.g., 100 cents to charge â‚¬1.00). The minimum amount is 1. The maximum amount is defined by user's daily/yearly limits.\n\n",
               "type": "integer",
               "example": 1250
            },
            "description": {
               "description": "Optional payment information to be displayed in MobilePay app\nto the customer. This can be, for example, an invoice number, ticket number,\nor short description that uniquely identifies the purchase.",
               "type": "string",
               "example": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            "paymentPointId": {
               "format": "uuid",
               "description": "The payment point on which payment was initiated.\n\n",
               "type": "string",
               "example": "7347ba06-95c5-4181-82e5-7c7a23609a0e"
            },
            "reference": {
               "description": "Payment's reference provided by you.\n\n",
               "type": "string",
               "example": "My-Payment-1"
            },
            "mobilePayAppRedirectUri": {
               "description": "Deeplink is used to redirect MobilePay users back to the merchant's app.\n\n",
               "type": "string",
               "example": "mobilepay://merchant_payments?payment_id=186d2b31-ff25-4414-9fd1-bfe9807fa8b7"
            },
            "state": {
               "format": "string",
               "description": "Indicates whether the payment is \"initiated\", \"reserved\", \"captured\", \"cancelledByMerchant\", \"cancelledBySystem\", \"cancelledByUser\".\n",
               "enum": [
                  "initiated",
                  "reserved",
                  "captured",
                  "cancelledByMerchant",
                  "cancelledByUser",
                  "cancelledBySystem"
               ],
               "type": "string",
               "example": "initiated"
            },
            "initiatedOn": {
               "format": "date-time",
               "description": "The timestamp of when the payment was created, in ISO 8601-1:2019\nformat.<br />\r\nExamples for July 19th, 2021 12:42:38am Pacific Standard\nTime:<br />\r\nUTC: 2021-07-19T12:42:38Z\n\n",
               "type": "string",
               "example": "2021-09-27T11:42:22Z"
            },
            "lastUpdatedOn": {
               "format": "date-time",
               "description": "The timestamp of when the payment was created, in ISO 8601-1:2019 format.\n\n",
               "type": "string",
               "example": "2021-09-27T11:42:22Z"
            },
            "merchantId": {
               "format": "uuid",
               "description": "Merchant ID associated with the payment.\n\n",
               "type": "string",
               "example": "655ad36f-70b0-4add-a123-b943daca50e8"
            },
            "isoCurrencyCode": {
               "description": "Three-letter ISO currency code in uppercase.<br />\r\nPossible\nvalues:<br />\r\n\"DKK\",<br />\r\n\"EUR\"\n\n",
               "type": "string",
               "example": "DKK"
            },
            "paymentPointName": {
               "description": "Payment point name displayed to the user in MobilePay app.\n\n",
               "type": "string",
               "example": "MyPaymentPoint"
            }
         }
      },
      "InitiatePaymentRequest": {
         "description": "<table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>amount</code></td><td><strong>Required</strong></td><td>number\n(integer)</td><td>The amount of money to be collected by this payment.<br>A\npositive integer representing how much to charge in the smallest currency unit\n(e.g., 100 cents to charge â‚¬1.00). The minimum amount is 1. The maximum amount\nis defined by user's daily/yearly limits.\n\n</td></tr><tr><td><code>idempotencyKey</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>A unique value that identifies this InitiatePayment request.\nMust be a valid GUID, and is used to protect against accidental duplicate calls.\nMultiple requests with the same idempotency key have the same result.\n\n</td></tr><tr><td><code>paymentPointId</code></td><td><strong>Required</strong></td><td>string\n(uuid)</td><td>The Payment Point ID to associate with a payment.\n\n</td></tr><tr><td><code>redirectUri</code></td><td><strong>Required</strong></td><td>string</td><td>MobilePay\nwill use the redirectUri URL to redirect the MobilePay user to the merchant's\nconfirmation page once user action is completed in MobilePay app. Must be a\nvalid URI.</td></tr><tr><td><code>reference</code></td><td><strong>Required</strong></td><td>string</td><td>An\nID to associate with the payment. Max length: 64 characters.<br />\r\nYou can\nuse this field to associate the payment to an entity in an external system (for\nexample, you might specify an order ID that is generated by your system). It\nis recommended to use a unique value for each payment.\n\n</td></tr><tr><td><code>description</code></td><td>Optional</td><td>string</td><td>Optional\npayment information to be displayed in MobilePay app to the customer. Max length:\n200 characters.<br /> This can be, for example, an invoice number, ticket number,\nor short description that uniquely identifies the purchase.\n\n</td></tr></tbody></table>\n\n",
         "required": [
            "amount",
            "idempotencyKey",
            "paymentPointId",
            "redirectUri",
            "reference"
         ],
         "type": "object",
         "properties": {
            "amount": {
               "format": "int32",
               "description": "The amount of money to be collected by this payment.<br>A positive integer representing how much to charge in the smallest currency unit (e.g., 100 cents to charge â‚¬1.00). The minimum amount is 1. The maximum amount is defined by user's daily/yearly limits.\n\n",
               "type": "integer",
               "example": 1250
            },
            "description": {
               "description": "Optional payment information to be displayed in MobilePay app\nto the customer. Max length: 200 characters.<br />This can be, for example,\nan invoice number, ticket number, or short description that uniquely identifies\nthe purchase.",
               "maxLength": 200,
               "minLength": 0,
               "type": "string",
               "example": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            },
            "paymentPointId": {
               "format": "uuid",
               "description": "The Payment Point ID to associate with a payment.\n\n",
               "type": "string",
               "example": "7347ba06-95c5-4181-82e5-7c7a23609a0e"
            },
            "reference": {
               "description": "An ID to associate with the payment. Max length: 64 characters.<br\n/>\r\nYou can use this field to associate the payment to an entity in an\nexternal system (for example, you might specify an order ID that is generated\nby your system). It is recommended to use a unique value for each payment.\n\n",
               "maxLength": 64,
               "minLength": 0,
               "type": "string",
               "example": "My-Payment-1"
            },
            "idempotencyKey": {
               "format": "uuid",
               "description": "A unique value that identifies this InitiatePayment request. Must be a valid GUID, and is used to protect against accidental duplicate calls. Multiple requests with the same idempotency key have the same result.\n\n",
               "type": "string",
               "example": "fae7680f-9875-4ba9-8910-2f2e1791f390"
            },
            "redirectUri": {
               "description": "MobilePay will use the redirectUri URL to redirect the MobilePay\nuser to the merchant's confirmation page once user action is completed in\nMobilePay app. Must be a valid URI.",
               "maxLength": 2000,
               "minLength": 0,
               "type": "string",
               "example": "myapp://redirect"
            }
         }
      },
      "InitiatePaymentResponse": {
         "description": "<table style=\"table-layout: auto\"><thead><tr><th>Name</th><th>Usage</th><th>Type</th><th>Description</th></tr></thead><tbody><tr><td><code>mobilePayAppRedirectUri</code></td><td><strong>Required</strong></td><td>string</td><td>Deeplink to MobilePay app.\n\n</td></tr><tr><td><code>paymentId</code></td><td><strong>Required</strong></td><td>string (uuid)</td><td>A unique ID for the payment.\n\n</td></tr></tbody></table>\n\n",
         "required": [
            "mobilePayAppRedirectUri",
            "paymentId"
         ],
         "type": "object",
         "properties": {
            "paymentId": {
               "format": "uuid",
               "description": "A unique ID for the payment.\n\n",
               "type": "string",
               "example": "186d2b31-ff25-4414-9fd1-bfe9807fa8b7"
            },
            "mobilePayAppRedirectUri": {
               "description": "Deeplink to MobilePay app.\n\n",
               "type": "string",
               "example": "mobilepay://merchant_payments?payment_id=186d2b31-ff25-4414-9fd1-bfe9807fa8b7"
            }
         }
      }
   },
   "x-ibm-endpoints": [
      {
         "endpointUrl": "https://api.mobilepay.dk",
         "type": [
            "production",
            "development"
         ]
      }
   ]
}